language: php

matrix:
  include:
    - php: 7
      env: TYPO3=dev-master
    - php: 7
      env: TYPO3=^7.6.0
    - php: 5.6
      env: TYPO3=^7.6.0
    - php: 5.5
      env: TYPO3=^7.6.0
    - php: 5.6
      env: TYPO3=^6.2.0
    - php: 5.5
      env: TYPO3=^6.2.0
    - php: 5.4
      env: TYPO3=^6.2.0
    - php: 5.3
      env: TYPO3=^6.2.0

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - composer require typo3/cms="$TYPO3"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
   - >
     echo;
     echo "Running unit tests";
     .Build/bin/phpunit -c typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
   - >
     echo;
     echo "Running php lint";
     find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
   - >
     echo;
     export typo3DatabaseName="typo3";
     export typo3DatabaseHost="localhost";
     export typo3DatabaseUsername="root";
     export typo3DatabasePassword="";
     find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c typo3/sysext/core/Build/FunctionalTests.xml {}'
